# Site settings
title: thomas maillart -- research stuff
email: wazaahhh@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  thomas maillart -- research stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wazaahhh.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wazaahhh

# Build settings
markdown: kramdown


excerpt_separator: <!--more-->
