# Site settings
title: Thomas Maillart 
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Thomas Maillart
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wazaahhh.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wazaahhh

# Build settings
markdown: kramdown
